1: Create a 4X2 integer array and Prints its attributes
Note: The element must be a type of unsigned int16. And print the following
Attributes: –
 The shape of an array.
 Array dimensions.
 The Length of each element of the array in bytes.

In [4]:
import numpy

Array = numpy.empty([4,2], dtype = numpy.int16) 
print(Array)
print(" Array Shape is: ", Array.shape)
print(" Array dimensions: ",Array.ndim)
print(" Length of each element of array in bytes is ",Array.itemsize)

[[0 0]
 [0 0]
 [0 0]
 [1 0]]
 Array Shape is:  (4, 2)
 Array dimensions:  2
 Length of each element of array in bytes is  2


Create a 5X2 integer array from a range between 100
to 200 such that the difference between each element is 10

In [6]:
import numpy
Array1 = numpy.arange(100, 200, 10)
Array2 = Array1.reshape(5,2)
print (Array2)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


Exercise 3: Following is the provided numPy array. Return array of
items by taking the third column from all rows

sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

In [13]:
import numpy

Array1= numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) 
print(Array1)
Array2 = Array1[...,2]
print('the third colum', Array2)


[[11 22 33]
 [44 55 66]
 [77 88 99]]
the third colum [33 66 99]
