Pandas Exercises

In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/ds_salaries.csv')
df


Unnamed: 0  work_year experience_level employment_type  \
0             0       2020               MI              FT   
1             1       2020               SE              FT   
2             2       2020               SE              FT   
3             3       2020               MI              FT   
4             4       2020               SE              FT   
..          ...        ...              ...             ...   
602         602       2022               SE              FT   
603         603       2022               SE              FT   
604         604       2022               SE              FT   
605         605       2022               SE              FT   
606         606       2022               MI              FT   

                      job_title  salary salary_currency  salary_in_usd  \
0                Data Scientist   70000             EUR          79833   
1    Machine Learning Scientist  260000             USD         260000   
2             Big Data Engineer   85000             GBP         109024   
3          Product Data Analyst   20000             USD          20000   
4     Machine Learning Engineer  150000             USD         150000   
..                          ...     ...             ...            ...   
602               Data Engineer  154000             USD         154000   
603               Data Engineer  126000             USD         126000   
604                Data Analyst  129000             USD         129000   
605                Data Analyst  150000             USD         150000   
606                AI Scientist  200000             USD         200000   

    employee_residence  remote_ratio company_location company_size  
0                   DE             0               DE            L  
1                   JP             0               JP            S  
2                   GB            50               GB            M  
3                   HN             0               HN            S  
4                   US            50               US            L  
..                 ...           ...              ...          ...  
602                 US           100               US            M  
603                 US           100               US            M  
604                 US             0               US            M  
605                 US           100               US            M  
606                 IN           100               US            L  

[607 rows x 12 columns]

**1:the average of salary**

In [2]:
df1 = df["salary"].mean()
df1






324000.0626029654

2:Sort all salaries

In [3]:
df.sort_values('salary')


Unnamed: 0  work_year experience_level employment_type  \
238         238       2021               EN              FT   
185         185       2021               MI              FT   
15           15       2020               MI              FT   
124         124       2021               EN              PT   
196         196       2021               EN              FT   
..          ...        ...              ...             ...   
285         285       2021               SE              FT   
137         137       2021               MI              FT   
7             7       2020               MI              FT   
102         102       2021               MI              FT   
177         177       2021               MI              FT   

                job_title    salary salary_currency  salary_in_usd  \
238        Data Scientist      4000             USD           4000   
185         Data Engineer      4000             USD           4000   
15           Data Analyst      8000             USD           8000   
124          Data Analyst      8760             EUR          10354   
196       BI Data Analyst      9272             USD           9272   
..                    ...       ...             ...            ...   
285  Data Science Manager   7000000             INR          94665   
137           ML Engineer   8500000             JPY          77364   
7          Data Scientist  11000000             HUF          35735   
102       BI Data Analyst  11000000             HUF          36259   
177        Data Scientist  30400000             CLP          40038   

    employee_residence  remote_ratio company_location company_size  
238                 VN             0               VN            M  
185                 IR           100               IR            M  
15                  PK            50               PK            L  
124                 ES            50               ES            M  
196                 KE           100               KE            S  
..                 ...           ...              ...          ...  
285                 IN            50               IN            L  
137                 JP            50               JP            S  
7                   HU            50               HU            L  
102                 HU            50               US            L  
177                 CL           100               CL            L  

[607 rows x 12 columns]

In [10]:
employe1={'name': ['ali', 'alaa'], 'age': [27, 24]}
df1 = pd.DataFrame(employe1)
employe2={'name': ['mo', 'ahmed'], 'age': [27,24]}
df2 = pd.DataFrame(employe2)
df1.merge(df2)
df1
df1['details'] = employe2
df1


name  age details
0   ali   27    name
1  alaa   24     age

Numpy Exercises

Split the array into four equal-sized sub-arrays 

**Note:** Create an 8X3 integer array from a range between10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.

In [11]:
import numpy as np
list1=[10,12,14,16,18,20,22,24,26,28,30,32,34]
a=np.array(list1)
a1=np.array_split(a, 4)
a1

[array([10, 12, 14, 16]),
 array([18, 20, 22]),
 array([24, 26, 28]),
 array([30, 32, 34])]

In [ ]:
%%shell
jupyter nbconvert --to html /content/